In [3]:
# Import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Importing the dataset
path = '/content/drive/MyDrive/Data Science/Proj_1/input_employees.csv'
df = pd.read_csv(path)
df.head()

   EmployeeID              Name   Department   Salary    JoinDate
0           1       Shane Chang        Sales  70000.0  2024-04-08
1           2    Zachary Wright           HR  50000.0  2016-12-30
2           3   Jennifer Moreno  Engineering  70000.0  2017-02-21
3           4      Keith Vargas        Sales      NaN  2018-03-22
4           5  Eugene Craig DDS        Sales  80000.0  2018-11-29

In [4]:
# Information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  100 non-null    int64
 1   Name        100 non-null    object
 2   Department  100 non-null    object
 3   Salary      90 non-null     float64
 4   JoinDate    100 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 4.0+ KB

In [ ]:
df.describe()

       EmployeeID        Salary
count  100.000000     90.000000
mean    50.250000  70444.444444
std     29.114672  14293.167309
min      1.000000  50000.000000
25%     25.750000  60000.000000
50%     49.500000  70000.000000
75%     75.250000  80000.000000
max    100.000000  90000.000000

In [ ]:
# Cleaning the dataset
## 1. Drop the duplicate row from the dataset
df.duplicated().sum()

0

In [ ]:
df.head()

   EmployeeID              Name   Department   Salary    JoinDate
0           1       Shane Chang        Sales  70000.0  2024-04-08
1           2    Zachary Wright           HR  50000.0  2016-12-30
2           3   Jennifer Moreno  Engineering  70000.0  2017-02-21
3           4      Keith Vargas        Sales      NaN  2018-03-22
4           5  Eugene Craig DDS        Sales  80000.0  2018-11-29

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  99 non-null     int64
 1   Name        99 non-null     object
 2   Department  99 non-null     object
 3   Salary      89 non-null     float64
 4   JoinDate    99 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 6.7+ KB

In [ ]:
## 2. Fill any missing values in the Salary column with the average salary of the department to which the employee belongs.
df.isnull().sum()

EmployeeID     0
Name           0
Department     0
Salary        10
JoinDate       0
dtype: int64

In [ ]:
### Fill the null values with mean salary, group by departments
df['Salary'] = df['Salary'].fillna(df.groupby('Department')['Salary'].transform('mean'))

In [ ]:
df.head(25)

    EmployeeID               Name   Department        Salary    JoinDate
0            1        Shane Chang        Sales  70000.000000  2024-04-08
1            2     Zachary Wright           HR  50000.000000  2016-12-30
2            3    Jennifer Moreno  Engineering  70000.000000  2017-02-21
3            4       Keith Vargas        Sales  67142.857143  2018-03-22
4            5   Eugene Craig DDS        Sales  80000.000000  2018-11-29
5            6    Patricia Howell  Engineering  70000.000000  2023-11-08
6            7    Catherine Ramos  Engineering  80000.000000  2014-12-29
7            8     Steven Mcclain           HR  80000.000000  2019-09-20
8            9       Harry Carter    Marketing  70000.000000  2017-09-02
9           10     William Turner           HR  90000.000000  2021-09-21
10          11      Melinda Reyes      Finance  70000.000000  2016-07-07
11          12      Albert Nelson      Finance  74761.904762  2019-06-15
12          13        Sarah Ponce    Marketing  80000.000000  2016-11-12
13          14  Michelle Castillo      Finance  60000.000000  2015-03-03
14          15  Christopher Lewis        Sales  67142.857143  2022-03-09
15          16       Timothy Kent      Finance  80000.000000  2021-11-06
16          17   Robert Robertson    Marketing  70000.000000  2022-01-30
17          18        Dana Macias           HR  80000.000000  2020-03-08
18          19       Amanda Davis    Marketing  70000.000000  2022-05-29
19          20     Matthew Palmer    Marketing  90000.000000  2018-04-14
20          21  Kristina Williams      Finance  80000.000000  2017-09-19
21          22       Misty Taylor  Engineering  60000.000000  2016-06-27
22          23      Gloria Palmer        Sales  50000.000000  2016-12-03
23          24      Jeremy Wright           HR  70000.000000  2016-04-07
24          25      Philip Wilson      Finance  90000.000000  2015-02-10

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  99 non-null     int64
 1   Name        99 non-null     object
 2   Department  99 non-null     object
 3   Salary      99 non-null     float64
 4   JoinDate    99 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 6.7+ KB

In [ ]:
## 3. Convert the JoinDate column to a datetime format.
df['JoinDate'] = pd.to_datetime(df['JoinDate'])

In [ ]:
df.head()

   EmployeeID              Name   Department        Salary   JoinDate
0           1       Shane Chang        Sales  70000.000000 2024-04-08
1           2    Zachary Wright           HR  50000.000000 2016-12-30
2           3   Jennifer Moreno  Engineering  70000.000000 2017-02-21
3           4      Keith Vargas        Sales  67142.857143 2018-03-22
4           5  Eugene Craig DDS        Sales  80000.000000 2018-11-29

In [ ]:
## 4. Create a new column Experience that calculates the number of years each employee hasbeen with the company, based on the JoinDate column and assuming the current year is 2024.
df['Experience'] = 2024 - df['JoinDate'].dt.year

In [ ]:
df.head()

,EmployeeID,Name,Department,Salary,JoinDate,Experience
0,1,Shane Chang,Sales,70000.000000,2024-04-08,0
1,2,Zachary Wright,HR,50000.000000,2016-12-30,8
2,3,Jennifer Moreno,Engineering,70000.000000,2017-02-21,7
3,4,Keith Vargas,Sales,67142.857143,2018-03-22,6
4,5,Eugene Craig DDS,Sales,80000.000000,2018-11-29,6

In [ ]:
### Convert df dataset to dictionary,
salary_column = df['Salary']

In [ ]:
# Mean (Average) Salary
mean_salary = salary_column.mean()

# Median Salary
median_salary = salary_column.median()

# Standard Deviation
std_deviation = salary_column.std()

# Minimum Salary
min_salary = salary_column.min()

# Maximum Salary
max_salary = salary_column.max()

In [ ]:
salary_statistics = {
    "mean_salary": mean_salary,
    "median_salary": median_salary,
    "std_deviation": std_deviation,
    "min_salary": min_salary,
    "max_salary": max_salary
}

In [ ]:
salary_statistics

{'mean_salary': 70177.00817700817,
 'median_salary': 70000.0,
 'std_deviation': 13503.121264430049,
 'min_salary': 50000.0,
 'max_salary': 90000.0}

In [ ]:
df['Salary'].describe()

count       99.000000
mean     70177.008177
std      13503.121264
min      50000.000000
25%      60000.000000
50%      70000.000000
75%      80000.000000
max      90000.000000
Name: Salary, dtype: float64

In [5]:
# Import the clean employees file
dfc=pd.read_csv('/content/drive/MyDrive/Data Science/Proj_1/cleaned_employees.csv')
dfc.head()

,EmployeeID,Name,Department,Salary,JoinDate,Experience
0,1,Shane Chang,Sales,70000.000000,2024-04-08,0
1,2,Zachary Wright,HR,50000.000000,2016-12-30,8
2,3,Jennifer Moreno,Engineering,70000.000000,2017-02-21,7
3,4,Keith Vargas,Sales,67142.857143,2018-03-22,6
4,5,Eugene Craig DDS,Sales,80000.000000,2018-11-29,6

In [7]:
# Extract relevant columns
experience_column = dfc['Experience']
salary_column = dfc['Salary']

In [8]:
# Calculate the Pearson correlation coefficient
correlation_coefficient = experience_column.corr(salary_column, method='pearson')

In [10]:
# Print the result
print(f"Pearson Correlation Coefficientbetween Experience and Salary: {correlation_coefficient:.4f}")

Pearson Correlation Coefficientbetween Experience and Salary: 0.0076

In [17]:
### Inferential Statistics - Confidence Interval for Mean Salary
import scipy.stats as stats
from scipy.stats import t

In [14]:
# Extract salary data
salary_column = dfc['Salary']

# Calculate sample mean and sample standard deviation
sample_mean = salary_column.mean()
sample_std = salary_column.std()

# Calculate sample size (number of employees)
n = len(salary_column)

# Calculate standard error
standard_error = sample_std / np.sqrt(n)

In [18]:
# Compute the confidence interval
confidence_level = 0.95
t_critical = t.ppf((1 + confidence_level) / 2, df=n - 1)
lower_bound = sample_mean - t_critical * standard_error
upper_bound = sample_mean + t_critical * standard_error

In [19]:
# Print the result
print(f"95% Confidence Interval for Mean Salary:")
print(f"Lower Bound: {lower_bound:.2f}")
print(f"Upper Bound: {upper_bound:.2f}")

95% Confidence Interval for Mean Salary:
Lower Bound: 67483.86
Upper Bound: 72870.16